[package]
name = "vcl_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["serde"] }
vcl_lib = { path = "../vcl_lib" }
tokio = { version = "1", features = ["rt", "time"] }
color-eyre = "0.6"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-appender = "0.2"
tracing-error = "0.2"
arboard = "3"
